stamina infer --algorithm rpni --drop --take 0.03 --score grid/32-0.test.adl grid/32-0.training.adl
stamina infer --algorithm bluefringe --drop --take 0.03 --score grid/32-0.test.adl grid/32-0.training.adl
stamina infer --algorithm rpni --drop --take 0.06 --score grid/32-0.test.adl grid/32-0.training.adl
stamina infer --algorithm bluefringe --drop --take 0.06 --score grid/32-0.test.adl grid/32-0.training.adl
stamina infer --algorithm rpni --drop --take 0.125 --score grid/32-0.test.adl grid/32-0.training.adl
stamina infer --algorithm bluefringe --drop --take 0.125 --score grid/32-0.test.adl grid/32-0.training.adl
stamina infer --algorithm rpni --drop --take 0.25 --score grid/32-0.test.adl grid/32-0.training.adl
stamina infer --algorithm bluefringe --drop --take 0.25 --score grid/32-0.test.adl grid/32-0.training.adl
stamina infer --algorithm rpni --drop --take 0.5 --score grid/32-0.test.adl grid/32-0.training.adl
stamina infer --algorithm bluefringe --drop --take 0.5 --score grid/32-0.test.adl grid/32-0.training.adl
stamina infer --algorithm rpni --drop --take 1.0 --score grid/32-0.test.adl grid/32-0.training.adl
stamina infer --algorithm bluefringe --drop --take 1.0 --score grid/32-0.test.adl grid/32-0.training.adl
stamina infer --algorithm rpni --drop --take 0.03 --score grid/32-1.test.adl grid/32-1.training.adl
stamina infer --algorithm bluefringe --drop --take 0.03 --score grid/32-1.test.adl grid/32-1.training.adl
stamina infer --algorithm rpni --drop --take 0.06 --score grid/32-1.test.adl grid/32-1.training.adl
stamina infer --algorithm bluefringe --drop --take 0.06 --score grid/32-1.test.adl grid/32-1.training.adl
stamina infer --algorithm rpni --drop --take 0.125 --score grid/32-1.test.adl grid/32-1.training.adl
stamina infer --algorithm bluefringe --drop --take 0.125 --score grid/32-1.test.adl grid/32-1.training.adl
stamina infer --algorithm rpni --drop --take 0.25 --score grid/32-1.test.adl grid/32-1.training.adl
stamina infer --algorithm bluefringe --drop --take 0.25 --score grid/32-1.test.adl grid/32-1.training.adl
stamina infer --algorithm rpni --drop --take 0.5 --score grid/32-1.test.adl grid/32-1.training.adl
stamina infer --algorithm bluefringe --drop --take 0.5 --score grid/32-1.test.adl grid/32-1.training.adl
stamina infer --algorithm rpni --drop --take 1.0 --score grid/32-1.test.adl grid/32-1.training.adl
stamina infer --algorithm bluefringe --drop --take 1.0 --score grid/32-1.test.adl grid/32-1.training.adl
stamina infer --algorithm rpni --drop --take 0.03 --score grid/32-2.test.adl grid/32-2.training.adl
stamina infer --algorithm bluefringe --drop --take 0.03 --score grid/32-2.test.adl grid/32-2.training.adl
stamina infer --algorithm rpni --drop --take 0.06 --score grid/32-2.test.adl grid/32-2.training.adl
stamina infer --algorithm bluefringe --drop --take 0.06 --score grid/32-2.test.adl grid/32-2.training.adl
stamina infer --algorithm rpni --drop --take 0.125 --score grid/32-2.test.adl grid/32-2.training.adl
stamina infer --algorithm bluefringe --drop --take 0.125 --score grid/32-2.test.adl grid/32-2.training.adl
stamina infer --algorithm rpni --drop --take 0.25 --score grid/32-2.test.adl grid/32-2.training.adl
stamina infer --algorithm bluefringe --drop --take 0.25 --score grid/32-2.test.adl grid/32-2.training.adl
stamina infer --algorithm rpni --drop --take 0.5 --score grid/32-2.test.adl grid/32-2.training.adl
stamina infer --algorithm bluefringe --drop --take 0.5 --score grid/32-2.test.adl grid/32-2.training.adl
stamina infer --algorithm rpni --drop --take 1.0 --score grid/32-2.test.adl grid/32-2.training.adl
stamina infer --algorithm bluefringe --drop --take 1.0 --score grid/32-2.test.adl grid/32-2.training.adl
stamina infer --algorithm rpni --drop --take 0.03 --score grid/32-3.test.adl grid/32-3.training.adl
stamina infer --algorithm bluefringe --drop --take 0.03 --score grid/32-3.test.adl grid/32-3.training.adl
stamina infer --algorithm rpni --drop --take 0.06 --score grid/32-3.test.adl grid/32-3.training.adl
stamina infer --algorithm bluefringe --drop --take 0.06 --score grid/32-3.test.adl grid/32-3.training.adl
stamina infer --algorithm rpni --drop --take 0.125 --score grid/32-3.test.adl grid/32-3.training.adl
stamina infer --algorithm bluefringe --drop --take 0.125 --score grid/32-3.test.adl grid/32-3.training.adl
stamina infer --algorithm rpni --drop --take 0.25 --score grid/32-3.test.adl grid/32-3.training.adl
stamina infer --algorithm bluefringe --drop --take 0.25 --score grid/32-3.test.adl grid/32-3.training.adl
stamina infer --algorithm rpni --drop --take 0.5 --score grid/32-3.test.adl grid/32-3.training.adl
stamina infer --algorithm bluefringe --drop --take 0.5 --score grid/32-3.test.adl grid/32-3.training.adl
stamina infer --algorithm rpni --drop --take 1.0 --score grid/32-3.test.adl grid/32-3.training.adl
stamina infer --algorithm bluefringe --drop --take 1.0 --score grid/32-3.test.adl grid/32-3.training.adl
stamina infer --algorithm rpni --drop --take 0.03 --score grid/32-4.test.adl grid/32-4.training.adl
stamina infer --algorithm bluefringe --drop --take 0.03 --score grid/32-4.test.adl grid/32-4.training.adl
stamina infer --algorithm rpni --drop --take 0.06 --score grid/32-4.test.adl grid/32-4.training.adl
stamina infer --algorithm bluefringe --drop --take 0.06 --score grid/32-4.test.adl grid/32-4.training.adl
stamina infer --algorithm rpni --drop --take 0.125 --score grid/32-4.test.adl grid/32-4.training.adl
stamina infer --algorithm bluefringe --drop --take 0.125 --score grid/32-4.test.adl grid/32-4.training.adl
stamina infer --algorithm rpni --drop --take 0.25 --score grid/32-4.test.adl grid/32-4.training.adl
stamina infer --algorithm bluefringe --drop --take 0.25 --score grid/32-4.test.adl grid/32-4.training.adl
stamina infer --algorithm rpni --drop --take 0.5 --score grid/32-4.test.adl grid/32-4.training.adl
stamina infer --algorithm bluefringe --drop --take 0.5 --score grid/32-4.test.adl grid/32-4.training.adl
stamina infer --algorithm rpni --drop --take 1.0 --score grid/32-4.test.adl grid/32-4.training.adl
stamina infer --algorithm bluefringe --drop --take 1.0 --score grid/32-4.test.adl grid/32-4.training.adl
stamina infer --algorithm rpni --drop --take 0.03 --score grid/64-0.test.adl grid/64-0.training.adl
stamina infer --algorithm bluefringe --drop --take 0.03 --score grid/64-0.test.adl grid/64-0.training.adl
stamina infer --algorithm rpni --drop --take 0.06 --score grid/64-0.test.adl grid/64-0.training.adl
stamina infer --algorithm bluefringe --drop --take 0.06 --score grid/64-0.test.adl grid/64-0.training.adl
stamina infer --algorithm rpni --drop --take 0.125 --score grid/64-0.test.adl grid/64-0.training.adl
stamina infer --algorithm bluefringe --drop --take 0.125 --score grid/64-0.test.adl grid/64-0.training.adl
stamina infer --algorithm rpni --drop --take 0.25 --score grid/64-0.test.adl grid/64-0.training.adl
stamina infer --algorithm bluefringe --drop --take 0.25 --score grid/64-0.test.adl grid/64-0.training.adl
stamina infer --algorithm rpni --drop --take 0.5 --score grid/64-0.test.adl grid/64-0.training.adl
stamina infer --algorithm bluefringe --drop --take 0.5 --score grid/64-0.test.adl grid/64-0.training.adl
stamina infer --algorithm rpni --drop --take 1.0 --score grid/64-0.test.adl grid/64-0.training.adl
stamina infer --algorithm bluefringe --drop --take 1.0 --score grid/64-0.test.adl grid/64-0.training.adl
stamina infer --algorithm rpni --drop --take 0.03 --score grid/64-1.test.adl grid/64-1.training.adl
stamina infer --algorithm bluefringe --drop --take 0.03 --score grid/64-1.test.adl grid/64-1.training.adl
stamina infer --algorithm rpni --drop --take 0.06 --score grid/64-1.test.adl grid/64-1.training.adl
stamina infer --algorithm bluefringe --drop --take 0.06 --score grid/64-1.test.adl grid/64-1.training.adl
stamina infer --algorithm rpni --drop --take 0.125 --score grid/64-1.test.adl grid/64-1.training.adl
stamina infer --algorithm bluefringe --drop --take 0.125 --score grid/64-1.test.adl grid/64-1.training.adl
stamina infer --algorithm rpni --drop --take 0.25 --score grid/64-1.test.adl grid/64-1.training.adl
stamina infer --algorithm bluefringe --drop --take 0.25 --score grid/64-1.test.adl grid/64-1.training.adl
stamina infer --algorithm rpni --drop --take 0.5 --score grid/64-1.test.adl grid/64-1.training.adl
stamina infer --algorithm bluefringe --drop --take 0.5 --score grid/64-1.test.adl grid/64-1.training.adl
stamina infer --algorithm rpni --drop --take 1.0 --score grid/64-1.test.adl grid/64-1.training.adl
stamina infer --algorithm bluefringe --drop --take 1.0 --score grid/64-1.test.adl grid/64-1.training.adl
stamina infer --algorithm rpni --drop --take 0.03 --score grid/64-2.test.adl grid/64-2.training.adl
stamina infer --algorithm bluefringe --drop --take 0.03 --score grid/64-2.test.adl grid/64-2.training.adl
stamina infer --algorithm rpni --drop --take 0.06 --score grid/64-2.test.adl grid/64-2.training.adl
stamina infer --algorithm bluefringe --drop --take 0.06 --score grid/64-2.test.adl grid/64-2.training.adl
stamina infer --algorithm rpni --drop --take 0.125 --score grid/64-2.test.adl grid/64-2.training.adl
stamina infer --algorithm bluefringe --drop --take 0.125 --score grid/64-2.test.adl grid/64-2.training.adl
stamina infer --algorithm rpni --drop --take 0.25 --score grid/64-2.test.adl grid/64-2.training.adl
stamina infer --algorithm bluefringe --drop --take 0.25 --score grid/64-2.test.adl grid/64-2.training.adl
stamina infer --algorithm rpni --drop --take 0.5 --score grid/64-2.test.adl grid/64-2.training.adl
stamina infer --algorithm bluefringe --drop --take 0.5 --score grid/64-2.test.adl grid/64-2.training.adl
stamina infer --algorithm rpni --drop --take 1.0 --score grid/64-2.test.adl grid/64-2.training.adl
stamina infer --algorithm bluefringe --drop --take 1.0 --score grid/64-2.test.adl grid/64-2.training.adl
stamina infer --algorithm rpni --drop --take 0.03 --score grid/64-3.test.adl grid/64-3.training.adl
stamina infer --algorithm bluefringe --drop --take 0.03 --score grid/64-3.test.adl grid/64-3.training.adl
stamina infer --algorithm rpni --drop --take 0.06 --score grid/64-3.test.adl grid/64-3.training.adl
stamina infer --algorithm bluefringe --drop --take 0.06 --score grid/64-3.test.adl grid/64-3.training.adl
stamina infer --algorithm rpni --drop --take 0.125 --score grid/64-3.test.adl grid/64-3.training.adl
stamina infer --algorithm bluefringe --drop --take 0.125 --score grid/64-3.test.adl grid/64-3.training.adl
stamina infer --algorithm rpni --drop --take 0.25 --score grid/64-3.test.adl grid/64-3.training.adl
stamina infer --algorithm bluefringe --drop --take 0.25 --score grid/64-3.test.adl grid/64-3.training.adl
stamina infer --algorithm rpni --drop --take 0.5 --score grid/64-3.test.adl grid/64-3.training.adl
stamina infer --algorithm bluefringe --drop --take 0.5 --score grid/64-3.test.adl grid/64-3.training.adl
stamina infer --algorithm rpni --drop --take 1.0 --score grid/64-3.test.adl grid/64-3.training.adl
stamina infer --algorithm bluefringe --drop --take 1.0 --score grid/64-3.test.adl grid/64-3.training.adl
stamina infer --algorithm rpni --drop --take 0.03 --score grid/64-4.test.adl grid/64-4.training.adl
stamina infer --algorithm bluefringe --drop --take 0.03 --score grid/64-4.test.adl grid/64-4.training.adl
stamina infer --algorithm rpni --drop --take 0.06 --score grid/64-4.test.adl grid/64-4.training.adl
stamina infer --algorithm bluefringe --drop --take 0.06 --score grid/64-4.test.adl grid/64-4.training.adl
stamina infer --algorithm rpni --drop --take 0.125 --score grid/64-4.test.adl grid/64-4.training.adl
stamina infer --algorithm bluefringe --drop --take 0.125 --score grid/64-4.test.adl grid/64-4.training.adl
stamina infer --algorithm rpni --drop --take 0.25 --score grid/64-4.test.adl grid/64-4.training.adl
stamina infer --algorithm bluefringe --drop --take 0.25 --score grid/64-4.test.adl grid/64-4.training.adl
stamina infer --algorithm rpni --drop --take 0.5 --score grid/64-4.test.adl grid/64-4.training.adl
stamina infer --algorithm bluefringe --drop --take 0.5 --score grid/64-4.test.adl grid/64-4.training.adl
stamina infer --algorithm rpni --drop --take 1.0 --score grid/64-4.test.adl grid/64-4.training.adl
stamina infer --algorithm bluefringe --drop --take 1.0 --score grid/64-4.test.adl grid/64-4.training.adl
stamina infer --algorithm rpni --drop --take 0.03 --score grid/128-0.test.adl grid/128-0.training.adl
stamina infer --algorithm bluefringe --drop --take 0.03 --score grid/128-0.test.adl grid/128-0.training.adl
stamina infer --algorithm rpni --drop --take 0.06 --score grid/128-0.test.adl grid/128-0.training.adl
stamina infer --algorithm bluefringe --drop --take 0.06 --score grid/128-0.test.adl grid/128-0.training.adl
stamina infer --algorithm rpni --drop --take 0.125 --score grid/128-0.test.adl grid/128-0.training.adl
stamina infer --algorithm bluefringe --drop --take 0.125 --score grid/128-0.test.adl grid/128-0.training.adl
stamina infer --algorithm rpni --drop --take 0.25 --score grid/128-0.test.adl grid/128-0.training.adl
stamina infer --algorithm bluefringe --drop --take 0.25 --score grid/128-0.test.adl grid/128-0.training.adl
stamina infer --algorithm rpni --drop --take 0.5 --score grid/128-0.test.adl grid/128-0.training.adl
stamina infer --algorithm bluefringe --drop --take 0.5 --score grid/128-0.test.adl grid/128-0.training.adl
stamina infer --algorithm rpni --drop --take 1.0 --score grid/128-0.test.adl grid/128-0.training.adl
stamina infer --algorithm bluefringe --drop --take 1.0 --score grid/128-0.test.adl grid/128-0.training.adl
stamina infer --algorithm rpni --drop --take 0.03 --score grid/128-1.test.adl grid/128-1.training.adl
stamina infer --algorithm bluefringe --drop --take 0.03 --score grid/128-1.test.adl grid/128-1.training.adl
stamina infer --algorithm rpni --drop --take 0.06 --score grid/128-1.test.adl grid/128-1.training.adl
stamina infer --algorithm bluefringe --drop --take 0.06 --score grid/128-1.test.adl grid/128-1.training.adl
stamina infer --algorithm rpni --drop --take 0.125 --score grid/128-1.test.adl grid/128-1.training.adl
stamina infer --algorithm bluefringe --drop --take 0.125 --score grid/128-1.test.adl grid/128-1.training.adl
stamina infer --algorithm rpni --drop --take 0.25 --score grid/128-1.test.adl grid/128-1.training.adl
stamina infer --algorithm bluefringe --drop --take 0.25 --score grid/128-1.test.adl grid/128-1.training.adl
stamina infer --algorithm rpni --drop --take 0.5 --score grid/128-1.test.adl grid/128-1.training.adl
stamina infer --algorithm bluefringe --drop --take 0.5 --score grid/128-1.test.adl grid/128-1.training.adl
stamina infer --algorithm rpni --drop --take 1.0 --score grid/128-1.test.adl grid/128-1.training.adl
stamina infer --algorithm bluefringe --drop --take 1.0 --score grid/128-1.test.adl grid/128-1.training.adl
stamina infer --algorithm rpni --drop --take 0.03 --score grid/128-2.test.adl grid/128-2.training.adl
stamina infer --algorithm bluefringe --drop --take 0.03 --score grid/128-2.test.adl grid/128-2.training.adl
stamina infer --algorithm rpni --drop --take 0.06 --score grid/128-2.test.adl grid/128-2.training.adl
stamina infer --algorithm bluefringe --drop --take 0.06 --score grid/128-2.test.adl grid/128-2.training.adl
stamina infer --algorithm rpni --drop --take 0.125 --score grid/128-2.test.adl grid/128-2.training.adl
stamina infer --algorithm bluefringe --drop --take 0.125 --score grid/128-2.test.adl grid/128-2.training.adl
stamina infer --algorithm rpni --drop --take 0.25 --score grid/128-2.test.adl grid/128-2.training.adl
stamina infer --algorithm bluefringe --drop --take 0.25 --score grid/128-2.test.adl grid/128-2.training.adl
stamina infer --algorithm rpni --drop --take 0.5 --score grid/128-2.test.adl grid/128-2.training.adl
stamina infer --algorithm bluefringe --drop --take 0.5 --score grid/128-2.test.adl grid/128-2.training.adl
stamina infer --algorithm rpni --drop --take 1.0 --score grid/128-2.test.adl grid/128-2.training.adl
stamina infer --algorithm bluefringe --drop --take 1.0 --score grid/128-2.test.adl grid/128-2.training.adl
stamina infer --algorithm rpni --drop --take 0.03 --score grid/128-3.test.adl grid/128-3.training.adl
stamina infer --algorithm bluefringe --drop --take 0.03 --score grid/128-3.test.adl grid/128-3.training.adl
stamina infer --algorithm rpni --drop --take 0.06 --score grid/128-3.test.adl grid/128-3.training.adl
stamina infer --algorithm bluefringe --drop --take 0.06 --score grid/128-3.test.adl grid/128-3.training.adl
stamina infer --algorithm rpni --drop --take 0.125 --score grid/128-3.test.adl grid/128-3.training.adl
stamina infer --algorithm bluefringe --drop --take 0.125 --score grid/128-3.test.adl grid/128-3.training.adl
stamina infer --algorithm rpni --drop --take 0.25 --score grid/128-3.test.adl grid/128-3.training.adl
stamina infer --algorithm bluefringe --drop --take 0.25 --score grid/128-3.test.adl grid/128-3.training.adl
stamina infer --algorithm rpni --drop --take 0.5 --score grid/128-3.test.adl grid/128-3.training.adl
stamina infer --algorithm bluefringe --drop --take 0.5 --score grid/128-3.test.adl grid/128-3.training.adl
stamina infer --algorithm rpni --drop --take 1.0 --score grid/128-3.test.adl grid/128-3.training.adl
stamina infer --algorithm bluefringe --drop --take 1.0 --score grid/128-3.test.adl grid/128-3.training.adl
stamina infer --algorithm rpni --drop --take 0.03 --score grid/128-4.test.adl grid/128-4.training.adl
stamina infer --algorithm bluefringe --drop --take 0.03 --score grid/128-4.test.adl grid/128-4.training.adl
stamina infer --algorithm rpni --drop --take 0.06 --score grid/128-4.test.adl grid/128-4.training.adl
stamina infer --algorithm bluefringe --drop --take 0.06 --score grid/128-4.test.adl grid/128-4.training.adl
stamina infer --algorithm rpni --drop --take 0.125 --score grid/128-4.test.adl grid/128-4.training.adl
stamina infer --algorithm bluefringe --drop --take 0.125 --score grid/128-4.test.adl grid/128-4.training.adl
stamina infer --algorithm rpni --drop --take 0.25 --score grid/128-4.test.adl grid/128-4.training.adl
stamina infer --algorithm bluefringe --drop --take 0.25 --score grid/128-4.test.adl grid/128-4.training.adl
stamina infer --algorithm rpni --drop --take 0.5 --score grid/128-4.test.adl grid/128-4.training.adl
stamina infer --algorithm bluefringe --drop --take 0.5 --score grid/128-4.test.adl grid/128-4.training.adl
stamina infer --algorithm rpni --drop --take 1.0 --score grid/128-4.test.adl grid/128-4.training.adl
stamina infer --algorithm bluefringe --drop --take 1.0 --score grid/128-4.test.adl grid/128-4.training.adl
stamina infer --algorithm rpni --drop --take 0.03 --score grid/256-0.test.adl grid/256-0.training.adl
stamina infer --algorithm bluefringe --drop --take 0.03 --score grid/256-0.test.adl grid/256-0.training.adl
stamina infer --algorithm rpni --drop --take 0.06 --score grid/256-0.test.adl grid/256-0.training.adl
stamina infer --algorithm bluefringe --drop --take 0.06 --score grid/256-0.test.adl grid/256-0.training.adl
stamina infer --algorithm rpni --drop --take 0.125 --score grid/256-0.test.adl grid/256-0.training.adl
stamina infer --algorithm bluefringe --drop --take 0.125 --score grid/256-0.test.adl grid/256-0.training.adl
stamina infer --algorithm rpni --drop --take 0.25 --score grid/256-0.test.adl grid/256-0.training.adl
stamina infer --algorithm bluefringe --drop --take 0.25 --score grid/256-0.test.adl grid/256-0.training.adl
stamina infer --algorithm rpni --drop --take 0.5 --score grid/256-0.test.adl grid/256-0.training.adl
stamina infer --algorithm bluefringe --drop --take 0.5 --score grid/256-0.test.adl grid/256-0.training.adl
stamina infer --algorithm rpni --drop --take 1.0 --score grid/256-0.test.adl grid/256-0.training.adl
stamina infer --algorithm bluefringe --drop --take 1.0 --score grid/256-0.test.adl grid/256-0.training.adl
stamina infer --algorithm rpni --drop --take 0.03 --score grid/256-1.test.adl grid/256-1.training.adl
stamina infer --algorithm bluefringe --drop --take 0.03 --score grid/256-1.test.adl grid/256-1.training.adl
stamina infer --algorithm rpni --drop --take 0.06 --score grid/256-1.test.adl grid/256-1.training.adl
stamina infer --algorithm bluefringe --drop --take 0.06 --score grid/256-1.test.adl grid/256-1.training.adl
stamina infer --algorithm rpni --drop --take 0.125 --score grid/256-1.test.adl grid/256-1.training.adl
stamina infer --algorithm bluefringe --drop --take 0.125 --score grid/256-1.test.adl grid/256-1.training.adl
stamina infer --algorithm rpni --drop --take 0.25 --score grid/256-1.test.adl grid/256-1.training.adl
stamina infer --algorithm bluefringe --drop --take 0.25 --score grid/256-1.test.adl grid/256-1.training.adl
stamina infer --algorithm rpni --drop --take 0.5 --score grid/256-1.test.adl grid/256-1.training.adl
stamina infer --algorithm bluefringe --drop --take 0.5 --score grid/256-1.test.adl grid/256-1.training.adl
stamina infer --algorithm rpni --drop --take 1.0 --score grid/256-1.test.adl grid/256-1.training.adl
stamina infer --algorithm bluefringe --drop --take 1.0 --score grid/256-1.test.adl grid/256-1.training.adl
stamina infer --algorithm rpni --drop --take 0.03 --score grid/256-2.test.adl grid/256-2.training.adl
stamina infer --algorithm bluefringe --drop --take 0.03 --score grid/256-2.test.adl grid/256-2.training.adl
stamina infer --algorithm rpni --drop --take 0.06 --score grid/256-2.test.adl grid/256-2.training.adl
stamina infer --algorithm bluefringe --drop --take 0.06 --score grid/256-2.test.adl grid/256-2.training.adl
stamina infer --algorithm rpni --drop --take 0.125 --score grid/256-2.test.adl grid/256-2.training.adl
stamina infer --algorithm bluefringe --drop --take 0.125 --score grid/256-2.test.adl grid/256-2.training.adl
stamina infer --algorithm rpni --drop --take 0.25 --score grid/256-2.test.adl grid/256-2.training.adl
stamina infer --algorithm bluefringe --drop --take 0.25 --score grid/256-2.test.adl grid/256-2.training.adl
stamina infer --algorithm rpni --drop --take 0.5 --score grid/256-2.test.adl grid/256-2.training.adl
stamina infer --algorithm bluefringe --drop --take 0.5 --score grid/256-2.test.adl grid/256-2.training.adl
stamina infer --algorithm rpni --drop --take 1.0 --score grid/256-2.test.adl grid/256-2.training.adl
stamina infer --algorithm bluefringe --drop --take 1.0 --score grid/256-2.test.adl grid/256-2.training.adl
stamina infer --algorithm rpni --drop --take 0.03 --score grid/256-3.test.adl grid/256-3.training.adl
stamina infer --algorithm bluefringe --drop --take 0.03 --score grid/256-3.test.adl grid/256-3.training.adl
stamina infer --algorithm rpni --drop --take 0.06 --score grid/256-3.test.adl grid/256-3.training.adl
stamina infer --algorithm bluefringe --drop --take 0.06 --score grid/256-3.test.adl grid/256-3.training.adl
stamina infer --algorithm rpni --drop --take 0.125 --score grid/256-3.test.adl grid/256-3.training.adl
stamina infer --algorithm bluefringe --drop --take 0.125 --score grid/256-3.test.adl grid/256-3.training.adl
stamina infer --algorithm rpni --drop --take 0.25 --score grid/256-3.test.adl grid/256-3.training.adl
stamina infer --algorithm bluefringe --drop --take 0.25 --score grid/256-3.test.adl grid/256-3.training.adl
stamina infer --algorithm rpni --drop --take 0.5 --score grid/256-3.test.adl grid/256-3.training.adl
stamina infer --algorithm bluefringe --drop --take 0.5 --score grid/256-3.test.adl grid/256-3.training.adl
stamina infer --algorithm rpni --drop --take 1.0 --score grid/256-3.test.adl grid/256-3.training.adl
stamina infer --algorithm bluefringe --drop --take 1.0 --score grid/256-3.test.adl grid/256-3.training.adl
stamina infer --algorithm rpni --drop --take 0.03 --score grid/256-4.test.adl grid/256-4.training.adl
stamina infer --algorithm bluefringe --drop --take 0.03 --score grid/256-4.test.adl grid/256-4.training.adl
stamina infer --algorithm rpni --drop --take 0.06 --score grid/256-4.test.adl grid/256-4.training.adl
stamina infer --algorithm bluefringe --drop --take 0.06 --score grid/256-4.test.adl grid/256-4.training.adl
stamina infer --algorithm rpni --drop --take 0.125 --score grid/256-4.test.adl grid/256-4.training.adl
stamina infer --algorithm bluefringe --drop --take 0.125 --score grid/256-4.test.adl grid/256-4.training.adl
stamina infer --algorithm rpni --drop --take 0.25 --score grid/256-4.test.adl grid/256-4.training.adl
stamina infer --algorithm bluefringe --drop --take 0.25 --score grid/256-4.test.adl grid/256-4.training.adl
stamina infer --algorithm rpni --drop --take 0.5 --score grid/256-4.test.adl grid/256-4.training.adl
stamina infer --algorithm bluefringe --drop --take 0.5 --score grid/256-4.test.adl grid/256-4.training.adl
stamina infer --algorithm rpni --drop --take 1.0 --score grid/256-4.test.adl grid/256-4.training.adl
stamina infer --algorithm bluefringe --drop --take 1.0 --score grid/256-4.test.adl grid/256-4.training.adl
